{$IFNDEF PLAYERLIST}
{$DEFINE PLAYERLIST}
//,pl_apollo  in 'players\pl_apollo.pas'
//,pl_behold  in 'players\pl_behold.pas'
//,pl_lastfm  in 'players\pl_lastfm.pas'
//,pl_bs      in 'players\pl_bs.pas'
//,pl_itunes  in 'players\pl_itunes.pas'
,pl_la      in 'players\pl_la.pas'
,pl_1by1    in 'players\pl_1by1.pas'
,pl_mmonkey in 'players\pl_mmonkey.pas'
,pl_cowon   in 'players\pl_cowon.pas'
,pl_mpc     in 'players\pl_mpc.pas'
,pl_aimp    in 'players\pl_aimp.pas'
,pl_foobar  in 'players\pl_foobar.pas'
,pl_winamp  in 'players\pl_winamp.pas'
{$ENDIF}
